spring:
  application:
    name: awesomeshares
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/awesome_shares?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: awesomesharesdev
    password: awesomesharesdev
    driver-class-name: com.mysql.cj.jdbc.Driver